### ISSUE TITLE
Prices of items -> Specific Items

### ISSUE THREAD

**Issue by Martinmagi1** [michaelnpsp/KiwiFarm#11]
When running theres few things, mainly cloth, that are Common type, but i would like to put the Specific item to be AH price. 
But when i try to mouse over the Specific Items menu, nothing happends. No pop out menu like the rest of the options under "Prices of Items".

**Comment by michaelnpsp** [comment]
Can you tell me which item is failing , and in which game version and language ?
Can you enable the lua errors to see if some error is happening ? To enable errors type into chat:
/console scriptErrors 1
to disable the errors:
/console scriptErrors 0

**Comment by Martinmagi1** [comment]
Its not letting me pick any item. 
Its not doing anything at all. 
Wotlk Classic 3.4.0 English
No Lua Errors

--REMOVED YOUTUBE LINK--
In 20sec video i show how its acting. 
In this example i have Symbol of Kings in my inventory thats Common. But my goal is to change Runecloth to AH price insted of vendor price.

**Comment by michaelnpsp** [comment]
If you want to change the price source or set a custom price, you have to go to sesssions, daily, zones or totals submenu, for example:
**Right Click > Totals >  Items Looted > Select a quality > Select the Item > Click on the desired price sources.**
Keep in mind that items looted are moved to Totals, Zones and Daily sections when you finish a session, so If your session was not finished and you looted the item in that session, you have to go to Session instead of Totals (in 
Session usually there are less items too so it is more easy to locate a specific item),  you can use  Zones or Daily submenu too, for example:
**Right Click > Session > Items Looted > Selected quality > Select the item**
**Right Click > Zones > Dragonblight > Items Looted > Selected quality > Select the item**

**Comment by Martinmagi1** [comment]
Ahh thanks alot! I dident know it was like that it worked. Should work now, thanks alot :)

**Comment by michaelnpsp** [comment]
I forget to explain that the Price of Items submenu displays the items with a custom price assigned by the user. So if you want to change the price of the same item a second time, in this case the item should appear in the "Prices of Items" submenu.
